name: panchikawatta
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  card_swiper: ^3.0.1
  flutter_otp_text_field: ^1.1.3+2
  carousel_slider: ^4.2.1
  image_picker: ^1.1.1
  http: ^1.2.1
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.1
  intl: ^0.19.0
  image_cropper: ^7.0.5
  shared_preferences: any
  fluttertoast: any
  syncfusion_flutter_charts: ^26.1.40
  flutter_animation_progress_bar: ^2.3.1
  pie_chart: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/warning_lights/
    - lib/assets/profilePicture.jpg
    - lib/assets/vehicleDetails.jpeg
    - lib/src/img/orange logo 1.png
    - lib/src/img/profile.png
    - lib/src/img/uploadicon.png
    - lib/src/img/Whitelogo2.png
    - lib/src/img/vehicleDetails.jpeg
    - lib/src/img/Success.png
